<?php

/**
 * @var \Smartosc\HelloWorld\Block\Display $block
 */
$name = microtime(true);
$name = hash(sha512,$name);
//$name = password_hash($name, PASSWORD_BCRYPT);
//$name = preg_replace('/[^a-z0-9\-]/', '', $name);
$test = "Book or Amend My Appointment";
echo $name;
echo $block->sayHello();
?>
<div data-mage-init='{"myjs": {}}'>
    <a href="#" id="click-me">Click Me</a>
</div>


<div id="popup-modal" hidden>
    yes I am the modal.
</div>

<?php
echo "$test";echo "$test";echo "$test";echo "$test";echo "$test";
echo "$test";echo "$test";echo "$test";echo "$test";echo "$test";
echo "$test";echo "$test";echo "$test";echo "$test";echo "$test";
echo "$test";echo "$test";echo "$test";echo "$test";echo "$test";echo "$test";
echo "$test";
echo "$test";echo "$test";
echo "$test";
echo "$test";echo "$test";echo "$test";
echo "$test";
echo "$test";
echo "$test";
echo "$test";
echo "$test";



echo "tungnt6";
echo "tungnt6";
echo "tungnt6";
echo "tungnt6";echo "tungnt6";
echo "tungnt6";
echo "tungnt6";
echo "tungnt6";echo "tungnt6";
echo "tungnt6";
?>

<button type="button" class="action" data-trigger="trigger">
    <span data-bind="i18n: 'Click Here'"></span>
</button>
<div data-bind="mageInit: {
        'Magento_Ui/js/modal/modal':{
            'type': 'popup',
            'title': 'Popup title',
            'trigger': '[data-trigger=trigger]',
            'responsive': true,
            'buttons': [{
                text: jQuery.mage.__('Submit'),
                class: 'action'
            }]
        }}">
    <div class="content">
        Popup Content
    </div>
</div>

<div class="alert-modal-content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
</div>